### ISSUE TITLE
Crash: `Cannot invoke 'build' because "book" is null`

### ISSUE THREAD

**Issue by Krutoy242** [Ender-Development/PatchouliBooks#3]
Im trying to install PatchouliBooks to [E2EE](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) modpack.
I relpaced Patchouli with ROFL version and installed `patchoulibooks-0.2.1.jar`. Book defined [here](https://github.com/Krutoy242/Enigmatica2Expert-Extended/tree/master/patchouli_books/e2e_e).

Now game cant load and output this crash log: 
```ruby
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Patchouli (patchouli)
Caused by: java.lang.NullPointerException: Cannot invoke "vazkii.patchouli.common.book.Book.build(net.minecraftforge.fml.common.ModContainer, net.minecraft.util.ResourceLocation, boolean)" because "book" is null
    at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:82)
    at vazkii.patchouli.common.book.BookFolderLoader.findBooks(BookFolderLoader.java:35)
    at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:74)
    at vazkii.patchouli.common.base.CommonProxy.preInit(CommonProxy.java:29)
    at vazkii.patchouli.client.base.ClientProxy.preInit(ClientProxy.java:18)
    at vazkii.patchouli.common.base.Patchouli.preInit(Patchouli.java:39)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
```

[crash-2024-11-22_22.25.14-client.txt](https://github.com/user-attachments/files/17875440/crash-2024-11-22_22.25.14-client.txt)

**Comment by MasterEnderman** [comment]
Does this error occur if you only use patchouli rofl edition, without installing patchouli books? I tried to recreate the crash in dev, but it seem to occur even if I don't use my mod at all. So could you please confirm, that this is an issue related to patchouli books or with the base patchouli mod.

**Comment by Krutoy242** [comment]
No, this isnt happens when only ROFL installed. I [released modpack version](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended/files/5941073) with ROFL and it run fine, not only from my side but for other players too.
So, only ROFL = no crash. ROFL + your mod = crash.

**Comment by MasterEnderman** [comment]
Alright I was able to track down the issue, the fix will be uploaded shortly.

**Comment by MasterEnderman** [comment]
v0.2.2 is uploaded to [curseforge](https://www.curseforge.com/minecraft/mc-mods/patchouli-books/files/5947060)
